### ISSUE TITLE
Questions about dataset object

### ISSUE THREAD

**Issue by skurzhanskyi** [zhiqwang/image-captioning#11]
Hi, @zhiqwang 
Can you, please, explain what happens here?
https://github.com/zhiqwang/crnn.pytorch/blob/master/datasets/dataset.py#L53
After this batch target will always be 1D array, but according to the [documentation](https://pytorch.org/docs/stable/nn.html#torch.nn.CTCLoss) you need to return batch-wise 2D array.
For example, if you input ```([2], [3, 4])```, you will return ```[2, 3, 4]```

**Comment by zhiqwang** [comment]
Hi, @skurzhanskyi 

`target` can also be a `tensor` of size `(sum(target_lengths))`, the master branch of the [documentation](https://pytorch.org/docs/master/nn.html#torch.nn.CTCLoss) is clear. In this case, the targets are assumed to be un-padded and concatenated within 1 dimension. 

Also remarked in this documentation:
> In order to use CuDNN, `targets` must be in concatenated format.

**Comment by skurzhanskyi** [comment]
Oh, thanks. I see, so we get information about which number belongs to which example from `target_lengths`.
Just one more question: how data changes when [here](https://github.com/zhiqwang/crnn.pytorch/blob/master/datasets/dataset.py#L52) you stack?
I understand your explanation of `keep_ratio` parameter, but it seems that images have already fix dimension due to `Transform`

**Comment by zhiqwang** [comment]
After `Transform`, the image's shape can also be arbitrary, for example, suppose your image's width is bigger than height, when you set `transforms.Resize(32)`, then image will be rescaled to (32, 32 * width / height).

You can refer torchvision's documentation [here](https://pytorch.org/docs/master/torchvision/transforms.html#torchvision.transforms.Resize) and the code snippet [here](https://github.com/zhiqwang/crnn.pytorch/blob/c2f59119a1111acb3c3cc5efc5318369a125b783/main.py#L133).

Only in the fixed situation, the images can be stacked to be a batch. When you use the `--keep-ratio` parameter, the output of the datasets is just a tuple.

**Comment by skurzhanskyi** [comment]
Thanks a lot for the explanation.
