### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ronghui19** [zhiqwang/image-captioning#12]
`python ./main.py --dataset-root datasets --arch densenet121 --alphabet datasets/alphabet_decode_5990.txt --lr 5e-5 --optimizer rmsprop --gpu-id 6 --not-pretrained`

Traceback (most recent call last):
  File "./main.py", line 387, in <module>
    main()
  File "./main.py", line 209, in main
    _ = train(train_loader, model, criterion, optimizer, epoch)
  File "./main.py", line 274, in train
    loss = criterion(log_probs, targets, input_lengths, target_lengths)
  File "/home/ronghui/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ronghui/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 1248, in forward
    return F.ctc_loss(log_probs, targets, input_lengths, target_lengths, self.blank, self.reduction)
  File "/home/ronghui/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1732, in ctc_loss
    return torch.ctc_loss(log_probs, targets, input_lengths, target_lengths, blank, _Reduction.get_enum(reduction))
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by zhiqwang** [comment]
It seems that the memory for one operation is allocated in the different device. And I did't have multi GPU to reproduce this error.

Could you set
`CUDA_VISIBLE_DEVICES=6 python ./main.py --dataset-root datasets --arch densenet121 --alphabet datasets/alphabet_decode_5990.txt --lr 5e-5 --optimizer rmsprop --gpu-id 6 --not-pretrained`
or
`CUDA_VISIBLE_DEVICES=6 python ./main.py --dataset-root datasets --arch densenet121 --alphabet datasets/alphabet_decode_5990.txt --lr 5e-5 --optimizer rmsprop --gpu-id 0 --not-pretrained`?
I'm not sure which `gpu-id` should be chose here.

Another way is set `device = torch.device("cuda:{}".format(args.gpu_id))` in this [line](https://github.com/zhiqwang/crnn.pytorch/blob/c2f59119a1111acb3c3cc5efc5318369a125b783/main.py#L95), and could you please report more information about this error?

**Comment by XiaogangYin** [comment]
应该是显卡显存不够，    或者pytorch的bug
我用的是Tesla K40c, 数据集用的是mtwi_2018_train
>>> torch.__version__
'1.0.1.post2'

https://github.com/JuliaGPU/CUDAnative.jl/issues/160

nvidia-smi还报错：GPU 00000000:05:00.0: Detected Critical Xid Error  
加了这句，撑了9分钟
 if (targets.shape[0] > 24):
            continue
1.最后还是报错
targets, targets.shape[0]
tensor([ 270,   86,   86,  450,   20,  675,  675,  139, 1656,  372,  372,  344,
        1656,   71,   86,  107,   81,  695,  107,   81,   71,  248,   81,  372],
       dtype=torch.int32) 24
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/THC/generic/THCTensorMath.cu line=24 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "./main.py", line 389, in <module>
    main()
  File "./main.py", line 208, in main
    loss = train(train_loader, model, criterion, optimizer, epoch)
  File "./main.py", line 247, in train
    optimizer.zero_grad()
  File "/data/resys/anaconda2/envs/ocr/lib/python3.7/site-packages/torch/optim/optimizer.py", line 163, in zero_grad
    p.grad.zero_()
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/THC/generic/THCTensorMath.cu:24

**Comment by zhiqwang** [comment]
what is the result of reducing `batch_size` ?

**Comment by XiaogangYin** [comment]
I have already set batch_size = 1...

**Comment by zhiqwang** [comment]
Switch the version of pytorch to latest stable 1.1 version?

**Comment by kokoyy** [comment]
I got the same problem,  modify dataset.py line 40 to target = [int(i) for i in target]; line 53 to self.targets = torch.LongTensor(transposed_data[1]),  it works. But i got an nan loss later
i hope you can understand what am i talking about, forgive my poor english

**Comment by zhiqwang** [comment]
@kokoyy , According to the documentation of [CTCLoss](https://pytorch.org/docs/master/nn.html#ctcloss), after the modification of the Type from `IntTensor` to `LongTensor`, the computation of CTC is not by CUDNN.

And what's the parameter options and data you are using?
