### ISSUE TITLE
中文识别率不高是不是因为感受野的原因？

### ISSUE THREAD

**Issue by xiiiiiiii** [zhiqwang/image-captioning#17]
我用的模型是mobilenetv2,在这个网络中，block的重复次数是增加感受野的，我计算了一下你小尺寸的模型的感受野是139,但是图片的尺寸是32×280,一般来讲，感受野在64附近就是比较合适，这个感受野过大会不会是影响中文识别率不高的一个原因？感谢

**Comment by zhiqwang** [comment]
@xiiiiiiii 应该是，需要剪掉一层，先试一下 `densenet_cifar` 这个呢，这个感受野要小一半

**Comment by xiiiiiiii** [comment]
> @xiiiiiiii 应该是，需要剪掉一层，先试一下 `densenet_cifar` 这个呢，这个感受野要小一半

我剪掉了几层，计算了最后的感受野为67,宽度在经过mobilenet后变为了2*32,可是出现了nan的情况，求解答啊啊哭！

**Comment by zhiqwang** [comment]
原图是 `32 x 256`, 经过 mobilenet 变成 `2 x 32`, 是这个意思么？

**Comment by xiiiiiiii** [comment]
> 我看到一定需要使用 `mobilenet` 这个网络结构。如果只是测试，使用 `densenet_cifar` 这个目前得到的结果怎么样呢。
> BTW，原图是 `32 x 256`, 经过 mobilenet 变成 `2 x 32`, 是这个意思么？
是的，原图经过mobilenet变为2*32，感受野是67，啊啊刚才用densenet_cifar试了一下，显存爆了，但是我显存有10g，这个运算量这么大吗？这种情况我是不是只能改程序为多卡运行？
问题2，mobilenet试了一下把学习率从默认的1e-3改为了5e-5，loss没有出现nan的情况，这种情况是因为学习率设置的太大了吗？当然准确率是0,跑完了30个epoch，准确率是0,我这个是不是要增加epoch？
谢谢你

**Comment by xiiiiiiii** [comment]
> 原图是 `32 x 256`, 经过 mobilenet 变成 `2 x 32`, 是这个意思么？

是的，原图经过mobilenet变为2*32，感受野是67，啊啊刚才用densenet_cifar试了一下，显存爆了，但是我显存有10g，这个运算量这么大吗？这种情况我是不是只能改程序为多卡运行？
问题2，mobilenet试了一下把学习率从默认的1e-3改为了5e-5，loss没有出现nan的情况，这种情况是因为学习率设置的太大了吗？当然准确率是0,跑完了30个epoch，准确率是0,我这个是不是要增加epoch？
谢谢你

**Comment by zhiqwang** [comment]
`--batch-size` 先调小一些

先看一下 `densenet_cifar` 的结果

**Comment by zhiqwang** [comment]
这是使用的 alphabet 是多少类，5889?

**Comment by xiiiiiiii** [comment]
是6425类，前边的和你一样，后边又添加了些上去，我是取的开源cnocr里的alphabet，试了一下更小的batchsize，果然跑起来了，但准确率还是0,但是loss比mobilenet要小，因为我初学者想问一下，为什么batchsize变小了后所需要的显存就变小了？然后我问了下我朋友，朋友说我网络改错了，我再改改看看结果，有更好的结果我会提出来的～要是还不行的话我就要加rnn了

**Comment by xiiiiiiii** [comment]
> 这是使用的 alphabet 是多少类，5889?

是6425类，前边的和你一样，后边又添加了些上去，我是取的开源cnocr里的alphabet，试了一下更小的batchsize，果然跑起来了，但准确率还是0,但是loss比mobilenet要小，因为我初学者想问一下，为什么batchsize变小了后所需要的显存就变小了？然后我问了下我朋友，朋友说我网络改错了，我再改改看看结果，有更好的结果我会提出来的～要是还不行的话我就要加rnn了

**Comment by zhiqwang** [comment]
简单说 `batch_size` 是利用并行计算给 CNN, RNN 加速，并行计算需要消耗显存。

`rnn` 可以使用 https://github.com/zhiqwang/fairseq/tree/text-recognition 这里的框架

**Comment by zhiqwang** [comment]
CTCLoss 也建议更新最新的 pytorch，CTCLoss 实现有 bug, 讨论在 https://github.com/pytorch/pytorch/pull/21392

**Comment by xiiiiiiii** [comment]
> CTCLoss 也建议更新最新的pytorch，讨论在 [pytorch/pytorch#21392](https://github.com/pytorch/pytorch/pull/21392)

天哪！！你人也太好了吧！！！好的！！我再试试！！有更好的结果了我一定会和你及时交流的，有交流才能共同进步！！

**Comment by xiiiiiiii** [comment]
天哪！！你人也太好了吧！我可以加您微信来进行后续的交流吗？我现在是一名研二的学生，不过现在在北京实习呢，做的也是cc这一块，不过我刚入门，但是毕设和实习都是做ocr这一块的，想和你可以有机会的话进行后续的交流呀！我用mobilenet主要是为了它的速度，但这是实习公司的要求，我自己的话还是要把毕设做出来，所以最近一直在思考做这个，我可以加您微信进行交流吗？我不管我要先放我自己的微信！
我的微信号是 aabbcc281 名字叫牛奶厉害！感谢你！我可以加你吗？


我可不可以加你微信




 
---原始邮件---
发件人: "Zhiqiang Wang"<notifications@github.com>
发送时间: 2019年6月6日(星期四) 下午5:16
收件人: "zhiqwang/crnn.pytorch"<crnn.pytorch@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"guopeijun"<494207346@qq.com>;
主题: Re: [zhiqwang/crnn.pytorch] 中文识别率不高是不是因为感受野的原因？ (#17)



这是使用的 alphabet 是多少类，5889?

**Comment by yy9568** [comment]
@zhiqwang @xiiiiiiii  Hi, 这里提到的更新到最新的pytorch，是指通过pip install torch_nightly 吗？还是要从git上download 自己编译，期待回复，感谢！

**Comment by zhiqwang** [comment]
@zhouyuangan `pip install torch_nightly`

**Comment by yy9568** [comment]
@zhiqwang 谢谢！

**Comment by yy9568** [comment]
@zhiqwang 安装了torch_nightly，torchvision0.3没法使用了，遇到`ImportError: /usr/local/lib/python3.5/dist-packages/torchvision/_C.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106Device8validateEv`
请问你有遇到类似的情况吗？期待回复

**Comment by zhiqwang** [comment]
@zhouyuangan 遇到过这个问题，我现在的策略是先安装最新的torchvision（git clone ***/vision; cd vision; python setup install），torchvision安装的时候会安装 torch 1.1，然后把torch1.1 和 torch_nightly 都卸载了，再安装 torch_nightly.

https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py

这个文件可以检查你现在所有的 torch 环境，装完之后直接跑一下这个脚本，看环境还有冲突不

**Comment by yy9568** [comment]
@zhiqwang Hi，谢谢你的回复。我尝试了你说的方案，但我后来找到了更直接的方案，在pip install加上参数--no-deps，这可以阻止安装torch1.1.0。经过我的实验，最新的CTCLoss未能解决在我的数据集上出现的NaN。在此之前，我尝试过其他两个CTC版本如tensorflow版本，不会出现loss NaN。

**Comment by zhiqwang** [comment]
@zhouyuangan 也谢谢你的反馈。https://github.com/pytorch/pytorch/issues/18215 这里还有个对 nn.CTCLoss 的进一步，现在 pytorch 版本的 CTCLoss 应该还不是稳定的
