### ISSUE TITLE
Error(s) in loading state_dict for CRNN:

### ISSUE THREAD

**Issue by Bilgee** [zhiqwang/image-captioning#2]
I downloaded and tested the pretrained densenet model, but it showed the error messages.

Error(s) in loading state_dict for CRNN:
	Unexpected key(s) in state_dict: "features.1.denselayer1.norm1.num_batches_tracked", ...

**Comment by zhiqwang** [comment]
I guess you load the pretrained `densenet121` model with the scripts `python ./main.py --arch densenet121 --resume densenet121_pretrained.pth --test-only`?

The pretrained model just contain the `model.state_dict()`, which is not the resume checkpoint of the script `main.py` (It also contain `optimizer.state_dict()`).

One way to use the pretrained model is `demo.ipynb`, or modify `main.py` to load the model with parameter `model.load_state_dict(torch.load(PATH), strict=False)`.
