### ISSUE TITLE
annotation file format for English data

### ISSUE THREAD

**Issue by pp3993** [zhiqwang/image-captioning#5]
Please, can you share an example for training English text.
CHARMAP used for data include all variable [A-Z a-z0-9 :,>/-].  

```
target = torch.IntTensor([get_key(char_convert,i) for i in target])
TypeError: an integer is required (got type NoneType)

```

What should be the format of encoded data in annotation file after conversion?

**Comment by zhiqwang** [comment]
For example, there is an image named "00320_00091.jpg" in folder `[DATA]/images`, its constant is "99353361056742" (training data only contain number), the CHARMAP is `0123456789`, after conversion, there should be a line in the `[DATA]/train.txt` or `[DATA]/dev.txt`.

    00320_00091.jpg 10 10 4 6 4 4 7 2 1 6 7 8 5 3

**Remark.** the encoder code `0` is reserved for *ctc blank token*.

**Comment by zhiqwang** [comment]
BTW, As I mentioned in issue (#4), the current CNN base network is not suitable to recover image's spatial information, I will modify the network with decoder part soon.
