### ISSUE TITLE
Must the training data be of equal length? 

### ISSUE THREAD

**Issue by carry-xz** [zhiqwang/image-captioning#7]
Must the training data be of equal length? How to train unequal length labelling data?

**Comment by zhiqwang** [comment]
You can use the option `python ./main.py --keep-ratio` to keep the image spatial ratio when training.

I have test it in a small datasets (only contain numbers), but the result is bad.  Then, I train the network with fixed image size first, and proceed the training with all images keeping spatial ratio using trained checkpoint of fixed image size. But, the precision promote limited.

I didn't check the detail implementation of `nn.CTCLoss`. The current `nn.CTCLoss` implementation support variable `input_lengths`, you can refer to pytorch's implementation [here](https://pytorch.org/docs/master/nn.html#ctcloss)  and my call of `CTCLoss` [here](https://github.com/zhiqwang/crnn.pytorch/blob/a489fc8acc5ec9792ae933425eb1aa92ce037afe/main.py#L263).
