### ISSUE TITLE
训练结果在其他图片上的结果很差？

### ISSUE THREAD

**Issue by bagpeng** [zhiqwang/image-captioning#8]
我用你的模型测试其他图片，无法识别出里面的汉字。

**Comment by zhiqwang** [comment]
训练用的合成的汉字比较简单，场景受限吧，在你们用的文本数据上能再标记一批数据，进行训练么？

**Comment by bagpeng** [comment]
这个数据是怎么制作的呢？

**Comment by zhiqwang** [comment]
参考 [SynthText_Chinese_version](https://github.com/JarveeLee/SynthText_Chinese_version), [TextRecognitionDataGenerator](https://github.com/Belval/TextRecognitionDataGenerator), [text_renderer](https://github.com/Sanster/text_renderer)
